id: P1D81C834
initial_creation_type: input
source_metadata:
  title: Guru Yoga Series
  language: bo
  description: 'A series of Guru Yoga (bla ma''i rnal ''byor) practices:'
  volume:
    98740184287e42348855556750999b37:
      title: 'Bestower of Supreme Blessings: Guru Yoga of the Great Incomparable Lord
        Atiśa'
      parent: Atiśa Dīpaṃkara
    65d8c6daa44647e3b77fe7d18aaef19a:
      title: Guru Yoga of the Guru Mahāmuni
      parent: Buddha Śākyamuni
    2eb4cfd4ac3541adb1fbfd227c615f26:
      title: 'The Merry Sea of Blessings: A Guru Yoga of the Lord of Sages, Peerless
        Teacher of All, Including the Devas'
      parent: Buddha Śākyamuni
    043467349d6d4a979c710a8970eb09c8:
      title: A Profound and Concise Guru Yoga
      parent: Chatral Rinpoche
    01f1498c6c0d4f69a371f95eb53d192b:
      title: The Guru Yoga of the Profound Path
      parent: Dorje Tötreng Tsal
    166d21d2ed32439bb7b09ff70e02632f:
      title: 'The Gathering of Blessings: A Guru Yoga'
      parent: Dzogchen
    ec122f45e2e54c1ebdea7881f036ddb7:
      title: 'Guru Yoga: The Consummate Blessing'
      parent: Dzogchen
    421b40fb768d400bb1b7484ba02e9347:
      title: Guru Yoga
      parent: Padmasambhava
    800612ed4bca40ffaebf44e97f088fdd:
      title: 'A Drop of Jewels: A Guru Yoga for Lord Gampopa'
      parent: Gampopa Sonam Rinchen
    e2792b06026642a08d5ea29d064a0514:
      title: Guru Sādhana of Garab Dorje
      parent: Garab Dorje
    a68c40bdba6c4ce7be190a77e42645b9:
      title: 'A Shower of Wisdom: A Guru Yoga of Garab Dorje'
      parent: Garab Dorje
    377d7ba0fe434f95a472cdae3a406da3:
      title: 'The Swift Infusion of Blessings: A Guru Yoga of the Great Embodiment
        of Unchanging Awareness Wisdom'
      parent: Gesar
    01327c717c3941f6a6aeed499437f7c0:
      title: Guru Yoga of the Great Learned and Accomplished Ācārya Haribhadra
      parent: Haribhadra
    d0ce44a3ed2d4d63964d91422109d602:
      title: Guru Yoga – A Rang Rig Ma Chö
      parent: Jamyang Khyentse Chökyi Lodrö
    b524b99503344d12b0371b83db7637d7:
      title: Letter of Advice to Jamyang Gyaltsen
      parent: Jamyang Khyentse Chökyi Lodrö
    280694894a3341559d4041976c2b60d9:
      title: 'Bestowing the Glory of Wisdom: A Gaṇacakra Feast for Nyingtik Saldrön'
      parent: Jamyang Khyentse Chökyi Lodrö
    ea8cbeb027ec42148f4da6a7d5bc17f1:
      title: 'Drop of Wisdom Nectar: A Guru Yoga'
      parent: Jamyang Khyentse Chökyi Lodrö
    274abe8f4e7e487d9c2e19ecc7efb639:
      title: Guru Padma Yoga
      parent: Jamyang Khyentse Chökyi Lodrö
    0c955e7782134989a6aad1106a0b033b:
      title: 'The Bright Lamp of Wisdom: A Guide to the Practice of Guru Yoga (Yeshe
        Saldrön)'
      parent: Jamyang Khyentse Chökyi Lodrö
    46d5e31885d34cebb04388b0c8e41df2:
      title: 'The Bright Lamp of the Heart Essence (Nyingtik Saldrön): A Guru Yoga'
      parent: Jamyang Khyentse Chökyi Lodrö
    f8df4390ca744953b3c552cc475e9e65:
      title: Guru Yoga of Rigdzin Jigme Lingpa
      parent: Jigme Lingpa
    f54c317a6c24459b9249855427a539f9:
      title: 'The Swift Bestowal of Blessings: A Guru Yoga'
      parent: Khenchen Jigme Phuntsok
    bac2f5871cf3486a819d76a8f3d80a0f:
      title: Guru Yoga Focusing upon Noble Kurukullā
      parent: Kurukullā
    fb762fca987f4605b9afad29767e0f68:
      title: Guru Yoga of Jetsün Lochen, Queen of Yoginīs
      parent: Lochen Chönyi Zangmo
    16982aebd81a4b41b09d9de95a852458:
      title: Guru Yoga of the Great Omniscient One, Longchenpa
      parent: Longchen Rabjam
    6ef345dbca644aedb406ed4ecf5cc21e:
      title: 'Guru Yoga: The Complete Path of Sūtra And Tantra'
      parent: Mañjuśrī
    a7ed5010333849e69d67cede5b956a68:
      title: 'Vajra Net: The Ancillary Preliminary and Concluding Practices for the
        Three Drops, the Guru Yogas for Venerable Marpa, Mila, and Gampopa'
      parent: Marpa, Milarepa & Gampopa
    21403446d9414fe3826e7a7e8e8ba5ff:
      title: A Combined Guru Yoga for Marpa, Mila, and Gampopa
      parent: Marpa, Milarepa & Gampopa
    fa2771156057448594105d4a947d8996:
      title: Guru Yoga of Lord Marpa Lotsāwa
      parent: Marpa Chökyi Lodrö
    59d58297ca72426c81e4715a12c5b4ab:
      title: 'A Drop of Sunshine: A Guru Yoga for Lord Marpa'
      parent: Marpa Chökyi Lodrö
    015e06f3ad9e4f34ad483f1f9f610ff4:
      title: Guru Yoga of Jetsün Shepa Dorje
      parent: Milarepa
    4581e0f03a9c44709b8d678f7a37ae23:
      title: 'A Drop of Moonlight: A Guru Yoga for Lord Mila'
      parent: Milarepa
    1033df830bd54bf69eadd37695e15ffa:
      title: Supplication to Lord Mila Shepa Dorje
      parent: Milarepa
    675bbcf97cc342009d0069f2532d663b:
      title: Guru Yoga of Milarepa Shepa Dorje for Daily Practice
      parent: Milarepa
    29652282ad974a8ea9d28b4aac758698:
      title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
      parent: Mipham Rinpoche
    8b34968c91cd4a958d3275285cb2f711:
      title: 'The Radiant Treasure of Blessings: A Guru Yoga of the Great Vajradhara
        Ngawang Samten Lodrö'
      parent: Ngawang Samten Lodrö
    622dd5eb81774f278e81694f6bd3eb32:
      title: A Concise Guru Yoga
      parent: Padmasambhava
    b87aec465eaa498abd3f452bd9152f29:
      title: 'The Quintessence of the Profound Path: A Concise Guide to the Stages
        of Visualization for the Guru Yoga of the Seven-Line Supplication, A Shower
        of Blessings'
      parent: Padmasambhava
    6678df6f90c34cf095941c1f0c94680c:
      title: 'The Swift Infusion of Blessings: A Prayer and Aspiration for the Stages
        of the Path Combined with Guru Yoga'
      parent: Padmasambhava
    a6a8659f6eab472c84ba6fe41dd8ce89:
      title: 'The Wish-Fulfilling Jewel: The Outer Practice of Guru Yoga from the
        Heart-Essence of the Vast Expanse'
      parent: Padmasambhava
    8d742ab8226244bea3b9b21dd1d98109:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven-Line
        Prayer'
      parent: Padmasambhava
    108e15c869a2406da18a5f275290e16f:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven Line
        Prayer (Addendum)'
      parent: Padmasambhava
    30f77e770c5b457cb598f842af10053e:
      title: Guru Yoga of the Great Tertön Pema Lingpa
      parent: Pema Lingpa
    1dce86e2e1534501a5eba23162a493f0:
      title: 'Shower of Blessings: A Guru Yoga of the Great Paṇḍita, Glorious Rongzom'
      parent: Rongzom Chökyi Zangpo
    255c0873ef434ae0adcfbda4e9b30d66:
      title: 'The Sun of Ambrosial Wisdom: A Guru Yoga of Dharmarāja Sakya Paṇḍita'
      parent: Sakya Paṇḍita
    d22a60a3dd6b4b96b710708ee73e96bd:
      title: A Guru Yoga of Śavari
      parent: Śavari
    ef4e23e47b1a43628b5326cbadeb96b9:
      title: 'The Profound Path of Guru Yoga: A Way to Freedom for the Fortunate'
      parent: Sera Khandro
    285900b2dad04279b7047fc615b59b31:
      title: 'Great Treasury of Siddhis: A Guru Yoga of Paṇchen Smṛti'
      parent: Smṛtijñānakīrti
    268ff1b296344a0ca289e3c35b4c0658:
      title: 'Self-Arising Wisdom: Songtsen Gampo Guru Sādhana'
      parent: Songtsen Gampo
    b42ce43dfe8643348579e19a1f128956:
      title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the
        Three Deities of Long Life'
      parent: Three Deities of Long Life
    2ff11d99f3f34265bea6f97ce38f33a9:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Three Mañjughoṣas
    c6cab5c5fec0489aa436c1ead343b6ec:
      title: 'The Quintessential Blessing: A Guru Yoga'
      parent: Trulshik Rinpoche
    056998222975479b94dc5498c2abac84:
      title: Short Guru Yoga of the Noble Lord, All-Knowing Tsongkhapa
      parent: Tsongkhapa Lobzang Drakpa
    2bca534c987348e5994ce2b5fd164ed5:
      title: 'Cultivating the Pure Realm of Manifest Joy: A Guru Yoga of Vajrasattva'
      parent: Vajrasattva
created_at: '2022-03-01T03:55:16.218609'
last_modified_at: '2022-03-01T03:55:16.218623'
statistics:
  total_words: 47116
  total_non_words: 4627
quality:
  non_words_ratio: 0.1
